# Generated by Django 4.2.7 on 2026-06-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0003_create_superuser'),
    ]

    operations = [
    ]
