# Generated by Django 4.2.7 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_branch_alter_loan_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='late_penalty_rate',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='allow_early_repayment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='custom_frequency_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days between payments for custom frequency', null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='early_repayment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee percentage for early repayment', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after due date before penalty starts'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_overdue_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after which loan is marked as defaulted'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Penalty percentage per overdue period', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of total loan to pay per period', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=10),
        ),
    ]
